### ISSUE TITLE
Request for simple example for parsing xml with xsd definition

### ISSUE THREAD

**Issue by rohithmeethal** [thunderer/XSDragon#1]
Hi, can you please add a simple example or documentation for the package.
Thanks

**Comment by thunderer** [comment]
Hi @rohithmeethal, sorry for my late response. I will try to find time to write a documentation for this package, but I can't promise anything right now. In the meantime, did you encounter any specific problem I could help you with? I already used XSDragon to provide rock-solid SOAP API clients in the past, so if you provide me with your XSD schemas I could do some work for you. Thanks!

**Comment by rohithmeethal** [comment]
@thunderer thanks for getting back to me, I explored the generated files and found I just have to use the root node class to work :+1: 

I really appreciate that you put your valuable time on this package.
It saved a lot of time for me :clap:

I will try to add documentation myself in a week.

**Comment by thunderer** [comment]
Hi @rohithmeethal, I saw your comment in an email, but it is not here? Can you tell me what XSD package did you work with? I'm trying to find various examples of real-world schemas to test this library against. I'd be very grateful if you could send me yours.

I'm happy that you managed to work everything out on yourself. I already wrote a small example in the recent PR #2 on branch `next-minor`, still working on it though.

**Comment by rohithmeethal** [comment]
@thunderer Sorry, I deleted that comment because I used another package for my project. This is that package https://github.com/goetas-webservices/xsd2php
I assumed this was that package. Sorry for the confusion .
I worked with BmeCat 2005 xsd which you can find here https://www.bme.de/fileadmin/content/Initativen/BMEcat/Download_BMEcat_2005/bmecat_2005_xsd.zip

More details on the spec https://www.bme.de/initiativen/bmecat/download/
